listen_addresses = '*'
port = 5432

ssl = on
ssl_cert_file = '/certs/database/server.crt'
ssl_key_file = '/certs/database/server.key'
ssl_ca_file = '/certs/ca/ca.crt'

password_encryption = scram-sha-256

shared_preload_libraries = ''