/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as WaitingForOrganizationRouteImport } from './routes/waiting-for-organization'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin-dashboard'
import { Route as AuthenticatedAnalystDashboardRouteImport } from './routes/_authenticated.analyst-dashboard'
import { Route as AuthenticatedEmployeeDashboardRouteImport } from './routes/_authenticated.employee-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingForOrganizationRoute = WaitingForOrganizationRouteImport.update({
  id: '/waiting-for-organization',
  path: '/waiting-for-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin-dashboard',
    path: '/admin-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalystDashboardRoute =
  AuthenticatedAnalystDashboardRouteImport.update({
    id: '/analyst-dashboard',
    path: '/analyst-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeeDashboardRoute =
  AuthenticatedEmployeeDashboardRouteImport.update({
    id: '/employee-dashboard',
    path: '/employee-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waiting-for-organization': typeof WaitingForOrganizationRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/analyst-dashboard': typeof AuthenticatedAnalystDashboardRoute
  '/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waiting-for-organization': typeof WaitingForOrganizationRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/analyst-dashboard': typeof AuthenticatedAnalystDashboardRoute
  '/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/waiting-for-organization': typeof WaitingForOrganizationRoute
  '/_authenticated/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/analyst-dashboard': typeof AuthenticatedAnalystDashboardRoute
  '/_authenticated/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/waiting-for-organization'
    | '/admin-dashboard'
    | '/analyst-dashboard'
    | '/employee-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/waiting-for-organization'
    | '/admin-dashboard'
    | '/analyst-dashboard'
    | '/employee-dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/create-organization'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/waiting-for-organization'
    | '/_authenticated/admin-dashboard'
    | '/_authenticated/analyst-dashboard'
    | '/_authenticated/employee-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WaitingForOrganizationRoute: typeof WaitingForOrganizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-for-organization': {
      id: '/waiting-for-organization'
      path: '/waiting-for-organization'
      fullPath: '/waiting-for-organization'
      preLoaderRoute: typeof WaitingForOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-dashboard': {
      id: '/_authenticated/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analyst-dashboard': {
      id: '/_authenticated/analyst-dashboard'
      path: '/analyst-dashboard'
      fullPath: '/analyst-dashboard'
      preLoaderRoute: typeof AuthenticatedAnalystDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employee-dashboard': {
      id: '/_authenticated/employee-dashboard'
      path: '/employee-dashboard'
      fullPath: '/employee-dashboard'
      preLoaderRoute: typeof AuthenticatedEmployeeDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAnalystDashboardRoute: typeof AuthenticatedAnalystDashboardRoute
  AuthenticatedEmployeeDashboardRoute: typeof AuthenticatedEmployeeDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAnalystDashboardRoute: AuthenticatedAnalystDashboardRoute,
  AuthenticatedEmployeeDashboardRoute: AuthenticatedEmployeeDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CreateOrganizationRoute: CreateOrganizationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WaitingForOrganizationRoute: WaitingForOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
